---
- name: LINKLIGHT AS3
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: PUSH AS3
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ server_port }}/mgmt/shared/appsvcs/declare/AnsibleWorkshop"
        method: DELETE
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
