---
- name: BIG-IP Next Automation
  hosts: next-cm
  connection: httpapi
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  vars:
    ansible_host: bigip-next-hostname
    ansible_user: "{{ ansible_user }}"
    ansible_httpapi_password: "{{ ansible_password}}"
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.next.cm
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    as3_tenant_name: "WorkshopExample"
    F5_VIP_Name: Use-Case-1-VIP
    pool_members: "{{ groups['web'] }}"

  tasks:
    - name: Declaration with Next - AS3
      f5networks.next.cm_next_as3_deploy:
        content: "{{ lookup('template','j2/https.j2', split_lines=False) }}"
        target_ip: "{{item.inventory_hostname}}"
      with_items: "{{ groups['next-instances'] }}"