---
# defaults file for ASM-Role

provider:
  server: "{{ private_ip }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  server_port: "{{ server_port }}"
  no_f5_teem: yes
  validate_certs: "no"

