---
- name: AS3 USECASE-1
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ server_port }}"
    as3_tenant_name: "WorkshopExample"
    F5_VIP_Name: Use-Case-1-VIP
    pool_members: "{{ groups['web'] }}"

  tasks:
    - name: Error Handling for AS3
      block:

        - name: PUSH AS3 Template
          f5networks.f5_bigip.bigip_as3_deploy:
            content: "{{ lookup('template','j2/https.j2', split_lines=False) }}"

      rescue:

        - name: RE-Install AS3 
          include: "Re-Install-AS3-2.yaml"

        - name: PUSH AS3 Template
          f5networks.f5_bigip.bigip_as3_deploy:
            content: "{{ lookup('template','j2/https.j2', split_lines=False) }}"
