---

- name: Backup BIG-IP Next instance
  f5networks.next.cm_next_backup_restore:
    #device_hostname: "{{ item.hostname }}"
    device_ip: "{{ item.address }}"
    filename: "{{ item.id }}.{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    #filename: "ansible.backup.tar.gz"
    file_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
    state: backup
    #force: true
    timeout: 600
  with_items: "{{ cm_info.managed_devices }}"
