---
- name: BIG-IP Next Automation
  hosts: next-cm
  connection: httpapi
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  vars:
    ansible_httpapi_password: '{{ lookup("env", "ANSIBLE_NET_SSH_KEYFILE") }}'
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.next.cm
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  roles:
    - f5_get_info
