---

#Re-Deploy ASM policy
  - name: Create an LTM policy
    f5networks.f5_modules.bigip_policy:
      provider: "{{ provider }}"
      name: "{{ ASM_Policy_Name }}"
      state: present
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Import ASM policy
    f5networks.f5_modules.bigip_asm_policy_import:
      provider: "{{ provider }}"
      name: "{{ ASM_Policy_Name }}"
      source: "{{ ASM_Policy_File }}"
      force: yes
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Replace a forward action with an ASM action
    f5networks.f5_modules.bigip_policy_rule:
      provider: "{{ provider }}"
      policy: "{{ ASM_Policy_Name }}"
      name: rule1
      actions:
      - type: enable
        asm_policy: "{{ ASM_Policy_Name }}"
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Deploy Draft ASM policy
    f5networks.f5_modules.bigip_policy:
      provider: "{{ provider }}"
      name: "{{ ASM_Policy_Name }}"
      state: present
      rules:
      - rule1
    when: Blocked_URLs is defined or Blocked_IPs is defined

#Assign ASM Policy to VIP
  - name: Update the HTTPS Virtual Server
    f5networks.f5_modules.bigip_virtual_server:
      provider: "{{ provider }}"
      state: present
      description: "HTTPS Virtual Server"
      name: "{{ F5_VIP_Name }}_https_vip"
      destination: "{{ private_ip }}"
      port: "{{ F5_VIP_Port }}"
      pool: "{{ F5_VIP_Name }}_pool"
      snat: Automap
      profiles:
       - http
       - oneconnect
       - name: clientssl
         context: client-side
       - websecurity
      policies:
       - "{{ ASM_Policy_Name }}"
    when: F5_VIP_Name is defined

#Apply Draft ASM policy
  - name: Activate ASM Policy
    f5networks.f5_modules.bigip_asm_policy_manage:
      provider: "{{ provider }}"
      name: "{{ ASM_Policy_Name }}"
      active: yes

#Publish ASM Policy via TMSH
  - name: Publish ASM Policy via TMSH
    f5networks.f5_modules.bigip_command:
      commands: "publish asm policy {{ ASM_Policy_Name }}"
      provider: "{{ provider }}"
