---

- name: ASM Policy Update with My Blocked IP
  hosts: next-cm
  connection: local
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  roles:
    - roles/Next-Roles/next_login
    - roles/Next-Roles/next_waf_block_ip
    - roles/Next-Roles/next_deploy_waf_policy
