---

- hosts: web
  gather_facts: false
  become: yes
  roles:
    - roles/Podman-Roles/install_podman
    - roles/Podman-Roles/install_juice_shop

- name: ASM Policy Update with Blocked IPs
  hosts: next-cm
  connection: local
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  roles:
    - roles/Next-Roles/next_login
    - roles/Next-Roles/next_create_waf_policy
    - roles/Next-Roles/next_get_waf_policy
    - roles/Next-Roles/next_waf_block_ip
    - roles/Next-Roles/next_deploy_waf_policy

- name: BIG-IP Next Automation - Use Case 4
  hosts: next-cm
  connection: httpapi
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  roles:
    - roles/Next-Roles/next_deploy_as3
