---
- name: AS3 Stacking Decarations
  hosts: lb
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml

  tasks:
       
    - name: add filenames to array
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/j2"
      register: file_array

    - name: Initialize combined_content variable
      ansible.builtin.set_fact:
        as3_app_body: ""

    - name: Find Latest File
      ansible.builtin.shell: ls {{ ASM_WebServer_File_Location }} -Artf | tail -n 1
      register: file_name
      delegate_to: node1

    - name: CREATE AS3 JSON BODY
      ansible.builtin.set_fact:
        as3_app_body: >-
          {{ as3_app_body + lookup('template', item.path, split_lines=false) + (',') }}
      with_items: "{{ file_array.files }}"
      when: "'base' not in item.path.split('/')[-1]"

    # - debug:
    #     var: as3_app_body

    - name: Change Communication
      ansible.builtin.set_fact:
        ansible_connection: httpapi

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/tenant_base.j2', split_lines=False) }}"