---
- name: AS3 USECASE-2
  hosts: lb
  connection: httpapi
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml

  tasks:

    # - name: create file array
    #   ansible.builtin.setfact:
    #     file_array: []
       
    - name: add filenames to array
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/j2"
      register: file_array

    # - name: debug
    #   ansible.builtin.debug:
    #     var: item.path.split('/')[-1] 
    #   with_items: "{{ file_array.files }}"
    #   when: item.path.split('/')[-1] is not search("base")

    # - name: Combine files into array 
    #   ansible.builtin.set_fact:
    #     combined: "{{ combined | default([]) + [item.path.split('/')[-1]] }}"
    #   with_items: "{{ file_array.files }}"
    #   when: "'base' not in item.path.split('/')[-1]"

    # - debug:
    #     var: file_array.files

    - name: Initialize combined_content variable
      ansible.builtin.set_fact:
        as3_app_body: ""

    - name: Read and combine file contents with commas
      ansible.builtin.set_fact:
        as3_app_body: >-
          {{ as3_app_body + lookup('template', item.path, split_lines=false) + (',') }}
      with_items: "{{ file_array.files }}"
      when: "'base' not in item.path.split('/')[-1]"

    # - debug:
    #     var: as3_app_body

    # - name: CREATE AS3 JSON BODY
    #   set_fact:
    #     as3_app_body: "{{ lookup('template', 'j2/as3_template.j2', split_lines=False) }}"
    #   with_items: 

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/tenant_base.j2', split_lines=False) }}"