---

- name: "Deploying WAF Policy - {{ waf_policy_name }}"
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/waf/v1/tasks/deploy-policy"
    method: POST
    body: '{"policy_name": "{{ waf_policy_name }}","comment": "This is a comment" }'
    status_code:
      - 201
    timeout: 300
    body_format: json
    headers:
      Authorization: "Bearer {{ login_info.json.access_token }}"
    validate_certs: false
  delegate_to: localhost
  register: waf_deployment

# - name: debug WAF_Deployment Output
#   ansible.builtin.debug:
#     var: waf_deployment
