- name: Pull Juiceshop Image with Podman
  containers.podman.podman_image:
    name: docker.io/bkimminich/juice-shop:latest

- name: Start Juiceshop Container in Podman
  containers.podman.podman_container:
    name: juice-shop-app
    image: docker.io/bkimminich/juice-shop:latest
    ports:
      - "{{ private_ip }}:3000:3000"
    state: started
    restart: true
