---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: ADD POOL MEMBERS
      f5networks.f5_modules.bigip_pool_member:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          validate_certs: false
        state: "present"
        name: "{{ hostvars[item].inventory_hostname }}"
        host: "{{ hostvars[item].private_ip }}"
        port: "80"
        pool: "http_pool"
      loop: "{{ groups['web'] }}"
