---

ansible_httpapi_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
ansible_httpapi_port: 443
ansible_network_os: f5networks.next.cm
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
