---

- name: Login to BIG-IP Next
  ansible.builtin.uri:
    url: " https://{{ ansible_host }}/api/login"
    method: POST
    body: '{"username": "{{ lookup("env", "ANSIBLE_NET_USERNAME") }}", "password": "{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}"}'
    status_code: 200
    timeout: 300
    body_format: json
    validate_certs: false
  delegate_to: localhost
  register: login_info
  # no_log: true

# - name: Debug Login Info
#   ansible.builtin.debug:
#     var: login_info
