---

provider:
  server: "{{ ansible_host }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  server_port: "{{ server_port }}"
  no_f5_teem: yes
  validate_certs: "no"

do_uri: "https://api.github.com/repos/F5Networks/f5-declarative-onboarding/releases/latest"
