---
# tasks file for Backup-Restore Role


- name: Find Latest UCS File
  ansible.builtin.shell: ls {{ local_folder_location }} -Artf | tail -n 1
  register: file_name
  delegate_to: localhost

- name: debug
  ansible.builtin.debug:
    var: file_name

#Ignore set due to Bug #1666 https://github.com/F5Networks/f5-ansible/issues/1666
- name: Restore UCS From Backup
  f5networks.f5_modules.bigip_ucs:
    ucs: "{{ file_name.stdout }}"
    state: installed
    no_license: true
    provider: "{{provider}}"
  delegate_to: localhost
  ignore_errors: true
  register: restored
  when: file_name.failed == false

- debug:
    msg: "Restore F5 Configuration FAILED do to backup file not found"
  when: file_name.failed == true
  tags:
    - restore

- debug:
    msg: "Restore Completed, Ignore Above Error in Restoration Section.  Reported bug at https://github.com/F5Networks/f5-ansible/issues/1666"
  when: file_name.failed == false
  tags:
    - restore
