---

- name: Create WAF Policy
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v1/spaces/default/security/waf-policies"
    method: POST
    body: '{"description": "My Ansible WAF Policy","enforcement_mode": "blocking", "application_language": "utf-8", "tags": [ "tag1" ], "case_insensitive": true, "name": "{{ waf_policy_name }}", "template_name": "RAPID-Template", "declaration": {}}'
    status_code:
      - 200
      - 400
    timeout: 300
    body_format: json
    headers:
      Authorization: "Bearer {{ login_info.json.access_token }}"
    validate_certs: false
  delegate_to: localhost
  register: waf_policies_info
  # no_log: true
