---
- name: BIG-IP Next Automation
  hosts: next-cm
  connection: httpapi
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  vars:
    ansible_httpapi_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.next.cm
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    as3_tenant_name: "Use-Case-2-SSL-App"
    pool_members: "{{ groups['web'] }}"
    SSL_Key: new-app-demo.key
    SSL_Cert: new-app-demo.crt
    vip_ip_address: 10.1.20.8

  tasks:

    - name: Collect users and files information on CM device
      f5networks.next.cm_device_info:
        gather_subset:
          - all
      register: cm_info

    # - name: Debug CM-Info
    #   ansible.builtin.debug:
    #     var: cm_info

    - name: Import Certificate/Key to Next
      f5networks.next.cm_ssl_certificate_import:
        name: Use-Case-2-Cert
        cert: "{{ playbook_dir }}/{{ SSL_Cert }}"
        key: "{{ playbook_dir }}/{{ SSL_Key }}"
        type: PEM
        update_cert: true
        update_key: true

    - name: Debug Declaration
      ansible.builtin.debug:
        msg: "{{ lookup('template', 'j2/cert_declaration.j2', split_lines=False) }}"

    - name: Declaration with Next - AS3
      f5networks.next.cm_next_as3_deploy:
        content: "{{ lookup('template', 'j2/cert_declaration.j2', split_lines=False) }}"
        target_ip: "{{ item.hostname }}"
      with_items: "{{ cm_info.managed_devices }}"
